# Generated by Django 5.1.3 on 2024-11-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editora',
            name='cnpj',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='editora',
            name='telefone',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='pessoafisica',
            name='cpf',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='pessoafisica',
            name='telefone',
            field=models.CharField(default=''),
        ),
    ]
